# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f31170cc8ea9f1f8c83ebe441489590b17a82e609ed0e06c8b561ae79018e7f9c627958fbb4b1358bbf2d0720a67908ca4829d4d8cd29406687ddc514bd6475

test:
  secret_key_base: c96d307bd0ad6e553dab4f90cab965013dd1e09f90ddd3c2f30174f40d6b75dac400e19ae8068d06eaec00206058e57581dd747805aaa3d7870f8c3b24913543

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
